// seedPlants.ts - Add category: "Indoor Plants" to each plant
const mongoose = require("mongoose");
const Plant = require("./models/SubPlants");
require("dotenv").config();

mongoose.connect(process.env.MONGODB_URI);

const indoorPlants = [
  {
    image: "/images/indoor/snake_plant.jpg",
    name: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    description:
      "NASA-approved air purifier that releases oxygen at night. Perfect for bedrooms. Extremely low maintenance.",
    features: {
      rawMaterial: ["Well-draining soil", "Terracotta pot"],
      temperature: "15-30°C",
      sunlight: "Low to bright indirect",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "High (nighttime O2 release)",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹499",
    deliveryBy: "2-4 days",
    offers: ["10% off first order", "Free plastic pot"],
  },
  {
    image: "/images/indoor/money_plant.jpg",
    name: "Money Plant",
    scientificName: "Epipremnum aureum",
    description:
      "Symbol of prosperity in Indian culture. Fast-growing, trailing vines perfect for hanging baskets.",
    features: {
      rawMaterial: ["Any potting mix", "Hanging basket"],
      temperature: "18-28°C",
      sunlight: "Low indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹199",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 get 1 free"],
  },
  {
    image: "/images/indoor/PeaceLily.jpg",
    name: "Peace Lily",
    scientificName: "Spathiphyllum",
    description:
      "Beautiful white flowers that indicate when it needs water. Excellent air purifier.",
    features: {
      rawMaterial: ["Rich potting soil"],
      temperature: "18-27°C",
      sunlight: "Low to medium indirect",
      waterFrequency: "When droops",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹399",
    originalPrice: "₹599",
    deliveryBy: "3-5 days",
    offers: ["Free ceramic pot"],
  },
  {
    image: "/images/indoor/ArecaPalm.jpg",
    name: "Areca Palm",
    scientificName: "Dypsis lutescens",
    description:
      "Tropical palm that humidifies air. Pet-safe and elegant for living rooms.",
    features: {
      rawMaterial: ["Palm soil mix"],
      temperature: "20-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Keep moist",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹799",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },
  {
    image: "/images/indoor/AloeVera.jpg",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    description:
      "Medicinal plant for skin burns. Succulent that stores water in leaves.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-30°C",
      sunlight: "Bright direct OK",
      waterFrequency: "Every 3 weeks",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹399",
    deliveryBy: "2-4 days",
    offers: ["Free terracotta pot"],
  },
  {
    image: "/images/indoor/ZZPlant.jpg",
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    description:
      "Drought-tolerant plant with glossy leaves. Perfect for low-light offices and apartments.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "18-30°C",
      sunlight: "Low to bright indirect",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹499",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/indoor/SpiderPlant.jpg",
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    description:
      "Easy-care plant producing baby plantlets. Excellent indoor air purifier.",
    features: {
      rawMaterial: ["Light potting soil"],
      temperature: "16-27°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/indoor/ChineseEvergreen.jpg",
    name: "Chinese Evergreen",
    scientificName: "Aglaonema commutatum",
    description:
      "Decorative foliage plant with colorful leaves. Great for low light.",
    features: {
      rawMaterial: ["Rich potting mix"],
      temperature: "18-29°C",
      sunlight: "Low to medium indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹449",
    deliveryBy: "3-5 days",
    offers: ["5% cashback"],
  },
  {
    image: "/images/indoor/Croton.jpg",
    name: "Croton",
    scientificName: "Codiaeum variegatum",
    description:
      "Bright multicolored foliage plant that adds vibrancy to interiors.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹399",
    deliveryBy: "3-5 days",
    offers: ["Free decorative pot"],
  },
  {
    image: "/images/indoor/ArrowheadPlant.jpg",
    name: "Arrowhead Plant",
    scientificName: "Syngonium podophyllum",
    description: "Fast-growing climber with arrow-shaped leaves.",
    features: {
      rawMaterial: ["Light potting mix"],
      temperature: "18-28°C",
      sunlight: "Medium indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },
  {
    image: "/images/indoor/RubberPlant.jpg",
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    description: "Large glossy leaves that remove toxins from indoor air.",
    features: {
      rawMaterial: ["Rich well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 7-10 days",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹599",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },
  {
    image: "/images/indoor/WeepingFig.jpg",
    name: "Weeping Fig",
    scientificName: "Ficus benjamina",
    description: "Elegant indoor tree with arching branches.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "16-28°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹699",
    deliveryBy: "4-6 days",
    offers: ["Free ceramic pot"],
  },
  {
    image: "/images/indoor/FiddleLeafFig.jpg",
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    description: "Trendy plant with large violin-shaped leaves.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹1299",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },
  {
    image: "/images/indoor/Monstera.jpg",
    name: "Monstera",
    scientificName: "Monstera deliciosa",
    description: "Swiss Cheese plant with unique split leaves.",
    features: {
      rawMaterial: ["Organic potting mix"],
      temperature: "20-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹899",
    deliveryBy: "4-6 days",
    offers: ["Free moss stick"],
  },
  {
    image: "/images/indoor/StringOfPearls.jpg",
    name: "String of Pearls",
    scientificName: "Senecio rowleyanus",
    description: "Trailing succulent with bead-like leaves.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Hanging pot included"],
  },
  {
    image: "/images/indoor/BostonFern.jpg",
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    description: "Lush fern ideal for humid environments.",
    features: {
      rawMaterial: ["Moist rich soil"],
      temperature: "18-26°C",
      sunlight: "Indirect light",
      waterFrequency: "Keep moist",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹499",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/indoor/BambooPalm.jpg",
    name: "Bamboo Palm",
    scientificName: "Chamaedorea seifrizii",
    description: "Graceful palm that filters indoor air toxins.",
    features: {
      rawMaterial: ["Palm soil mix"],
      temperature: "20-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹799",
    deliveryBy: "4-6 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/indoor/Philodendron.jpg",
    name: "Philodendron",
    scientificName: "Philodendron hederaceum",
    description: "Heart-shaped leaves, perfect for hanging or climbing.",
    features: {
      rawMaterial: ["Organic potting mix"],
      temperature: "18-28°C",
      sunlight: "Low to medium indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 1 get planter 50% off"],
  },
  {
    image: "/images/indoor/JadePlant.jpg",
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    description: "Succulent symbolizing prosperity and good luck.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-30°C",
      sunlight: "Bright light",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free terracotta pot"],
  },
  {
    image: "/images/indoor/Calathea.jpg",
    name: "Calathea",
    scientificName: "Calathea orbifolia",
    description: "Ornamental plant with patterned leaves.",
    features: {
      rawMaterial: ["Moist rich soil"],
      temperature: "18-26°C",
      sunlight: "Low to medium indirect",
      waterFrequency: "Keep moist",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹599",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },
  {
    image: "/images/indoor/Dieffenbachia.jpg",
    name: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    description: "Large decorative leaves with air-purifying qualities.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Medium indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/indoor/KentiaPalm.jpg",
    name: "Kentia Palm",
    scientificName: "Howea forsteriana",
    description: "Elegant slow-growing palm ideal for indoor decor.",
    features: {
      rawMaterial: ["Palm soil mix"],
      temperature: "18-27°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹1499",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },
  {
    image: "/images/indoor/EnglishIvy.jpg",
    name: "English Ivy",
    scientificName: "Hedera helix",
    description: "Climbing vine effective in removing airborne mold.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "15-25°C",
      sunlight: "Bright indirect",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹399",
    deliveryBy: "3-5 days",
    offers: ["Hanging basket included"],
  },
];

const outdoorPlantsData = [
  {
    image: "/images/outdoor/Bougainvillea.jpg",
    name: "Bougainvillea",
    scientificName: "Bougainvillea spectabilis",
    description:
      "Vibrant flowering climber ideal for gardens, walls, and balconies.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹399",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },
  {
    image: "/images/outdoor/Hibiscus.jpg",
    name: "Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    description: "Tropical flowering plant known for large colorful blooms.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "18-32°C",
      sunlight: "Full sun",
      waterFrequency: "Daily in summer",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/outdoor/Rose.jpg",
    name: "Rose",
    scientificName: "Rosa indica",
    description: "Classic garden flowering plant with fragrant blooms.",
    features: {
      rawMaterial: ["Rich garden soil"],
      temperature: "15-28°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2-3 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 get 5% off"],
  },
  {
    image: "/images/outdoor/Frangipani.jpg",
    name: "Frangipani / Champa",
    scientificName: "Plumeria rubra",
    description: "Fragrant flowering tree perfect for landscapes.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹799",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },
  {
    image: "/images/outdoor/Ixora.jpg",
    name: "Ixora",
    scientificName: "Ixora coccinea",
    description: "Dense flowering shrub ideal for hedges.",
    features: {
      rawMaterial: ["Acidic soil"],
      temperature: "20-30°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹399",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/outdoor/Lantana.jpg",
    name: "Lantana",
    scientificName: "Lantana camara",
    description: "Hardy flowering plant with multi-colored blooms.",
    features: {
      rawMaterial: ["Dry sandy soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    deliveryBy: "3-5 days",
    offers: ["Free pot"],
  },
  {
    image: "/images/outdoor/RoyalPalm.jpg",
    name: "Royal Palm",
    scientificName: "Roystonea regia",
    description: "Tall ornamental palm for avenues and large gardens.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "22-35°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹1499",
    deliveryBy: "6-8 days",
    offers: ["15% off"],
  },
  {
    image: "/images/outdoor/SagoPalm.jpg",
    name: "Sago Palm",
    scientificName: "Cycas revoluta",
    description: "Slow-growing ornamental plant for landscaping.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-32°C",
      sunlight: "Full sun / partial shade",
      waterFrequency: "Every 10 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹899",
    deliveryBy: "5-7 days",
    offers: ["10% discount"],
  },
  {
    image: "/images/outdoor/GoldenShowerTree.jpg",
    name: "Golden Shower Tree (Amaltas)",
    scientificName: "Cassia fistula",
    description: "Beautiful tree with cascading yellow flowers.",
    features: {
      rawMaterial: ["Garden soil"],
      temperature: "20-40°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹1299",
    deliveryBy: "6-8 days",
    offers: ["Free fertilizer pack"],
  },
  {
    image: "/images/outdoor/Jasmine.jpg",
    name: "Jasmine",
    scientificName: "Jasminum sambac",
    description: "Fragrant flowering plant used in garlands and gardens.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "18-30°C",
      sunlight: "Full sun / partial shade",
      waterFrequency: "Every 2 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
];

// 🌸 Flowering Plants Data
const floweringPlantsData = [
  {
    image: "/images/flower/rose.jpg",
    name: "Rose",
    scientificName: "Rosa indica",
    description:
      "Classic fragrant flowering plant available in multiple colors. Ideal for gardens and pots.",
    features: {
      rawMaterial: ["Rich garden soil", "Organic compost"],
      temperature: "15-28°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2-3 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 get 5% off"],
  },
  {
    image: "/images/flower/Marigold.jpg",
    name: "Marigold",
    scientificName: "Tagetes erecta",
    description:
      "Bright yellow and orange flowers commonly used in festivals and gardens.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "18-35°C",
      sunlight: "Full sun",
      waterFrequency: "Daily in summer",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹149",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/flower/Lotus.jpg",
    name: "Lotus",
    scientificName: "Nelumbo nucifera",
    description:
      "Sacred aquatic flowering plant with large pink or white blooms.",
    features: {
      rawMaterial: ["Clay soil", "Water container/pond"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Keep submerged",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹499",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },
  {
    image: "/images/flower/Hibiscus.jpg",
    name: "Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    description: "Tropical flowering shrub known for large vibrant blooms.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "18-32°C",
      sunlight: "Full sun",
      waterFrequency: "Daily in summer",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/flower/Jasmine.jpg",
    name: "Jasmine",
    scientificName: "Jasminum sambac",
    description:
      "Highly fragrant white flowers used in garlands and home gardens.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "18-30°C",
      sunlight: "Full sun / partial shade",
      waterFrequency: "Every 2 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free plastic pot"],
  },
  {
    image: "/images/flower/Sunflower.jpg",
    name: "Sunflower",
    scientificName: "Helianthus annuus",
    description:
      "Tall flowering plant with large yellow blooms that track the sun.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2 days",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹199",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/flower/Gulmohar.jpg",
    name: "Gulmohar",
    scientificName: "Delonix regia",
    description: "Large ornamental tree with striking red-orange flowers.",
    features: {
      rawMaterial: ["Garden soil"],
      temperature: "20-40°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹999",
    deliveryBy: "6-8 days",
    offers: ["Free fertilizer pack"],
  },
  {
    image: "/images/flower/Tuberose.jpg",
    name: "Tuberose (Rajnigandha)",
    scientificName: "Polianthes tuberosa",
    description: "Night-blooming fragrant flowering plant used in perfumes.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-30°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/flower/Dahlia.jpg",
    name: "Dahlia",
    scientificName: "Dahlia pinnata",
    description:
      "Colorful seasonal flowering plant with large decorative blooms.",
    features: {
      rawMaterial: ["Rich garden soil"],
      temperature: "15-25°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2-3 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹249",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 get 10% off"],
  },
  {
    image: "/images/flower/Petunia.jpg",
    name: "Petunia",
    scientificName: "Petunia hybrida",
    description:
      "Popular seasonal flowering plant ideal for hanging baskets and borders.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "15-30°C",
      sunlight: "Full sun",
      waterFrequency: "Every 2 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹199",
    deliveryBy: "3-5 days",
    offers: ["Free hanging pot"],
  },
];

const succulentsCactiData = [
  {
    image: "/images/SucculentsCacti/PricklyPearCactus.jpg",
    name: "Prickly Pear Cactus",
    scientificName: "Opuntia ficus-indica",
    description:
      "Hardy cactus with flat pads and edible fruits. Thrives in hot climates.",
    features: {
      rawMaterial: ["Sandy cactus soil"],
      temperature: "20-40°C",
      sunlight: "Full sun",
      waterFrequency: "Every 3 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹399",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },
  {
    image: "/images/SucculentsCacti/IndianFigCactus.jpg",
    name: "Indian Fig Cactus",
    scientificName: "Opuntia dillenii",
    description:
      "Spiny cactus producing edible fruits. Suitable for dry regions.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-40°C",
      sunlight: "Full sun",
      waterFrequency: "Every 3 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "4-6 days",
    offers: ["Free pot"],
  },
  {
    image: "/images/SucculentsCacti/BarrelCactus.jpg",
    name: "Barrel Cactus",
    scientificName: "Echinocactus grusonii",
    description:
      "Round cactus with golden spines. Popular ornamental desert plant.",
    features: {
      rawMaterial: ["Cactus mix"],
      temperature: "18-38°C",
      sunlight: "Full sun",
      waterFrequency: "Monthly",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹599",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },
  {
    image: "/images/SucculentsCacti/SaguaroCactus.jpg",
    name: "Saguaro Cactus",
    scientificName: "Carnegiea gigantea",
    description: "Tall iconic cactus species ideal for outdoor landscapes.",
    features: {
      rawMaterial: ["Well-draining sandy soil"],
      temperature: "22-40°C",
      sunlight: "Full sun",
      waterFrequency: "Monthly",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹999",
    deliveryBy: "6-8 days",
    offers: ["10% off"],
  },
  {
    image: "/images/SucculentsCacti/ChristmasCactus.jpg",
    name: "Christmas Cactus",
    scientificName: "Schlumbergera truncata",
    description: "Seasonal flowering cactus that blooms in winter.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "15-25°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free decorative pot"],
  },
  {
    image: "/images/SucculentsCacti/MoonCactus.jpg",
    name: "Moon Cactus",
    scientificName: "Gymnocalycium mihanovichii",
    description: "Colorful grafted cactus perfect for table décor.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/SucculentsCacti/HedgehogCactus.jpg",
    name: "Hedgehog Cactus",
    scientificName: "Echinopsis eyriesii",
    description: "Compact cactus with beautiful large flowers.",
    features: {
      rawMaterial: ["Cactus mix"],
      temperature: "18-35°C",
      sunlight: "Full sun",
      waterFrequency: "Every 3 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "4-6 days",
    offers: ["Free small pot"],
  },
  {
    image: "/images/SucculentsCacti/Cereus.jpg",
    name: "Cereus",
    scientificName: "Cereus repandus",
    description: "Tall columnar cactus suitable for outdoor gardens.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-38°C",
      sunlight: "Full sun",
      waterFrequency: "Monthly",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹699",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },
  {
    image: "/images/SucculentsCacti/Mammillaria.jpg",
    name: "Mammillaria",
    scientificName: "Mammillaria elongata",
    description: "Small cactus forming clusters with tiny flowers.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-32°C",
      sunlight: "Bright light",
      waterFrequency: "Every 3 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹249",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },
  {
    image: "/images/SucculentsCacti/DragonFruitCactus.jpg",
    name: "Dragon Fruit Cactus",
    scientificName: "Selenicereus undatus",
    description: "Climbing cactus producing exotic dragon fruits.",
    features: {
      rawMaterial: ["Well-draining sandy soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Free support stick"],
  },
  {
    image: "/images/SucculentsCacti/Echeveria.jpg",
    name: "Echeveria",
    scientificName: "Echeveria elegans",
    description: "Rosette-shaped decorative succulent.",
    features: {
      rawMaterial: ["Cactus mix"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹249",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },
  {
    image: "/images/SucculentsCacti/Haworthia.jpg",
    name: "Haworthia",
    scientificName: "Haworthiopsis attenuata",
    description: "Compact striped succulent ideal for desks.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-28°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free small pot"],
  },
  {
    image: "/images/SucculentsCacti/Kalanchoe.jpg",
    name: "Kalanchoe",
    scientificName: "Kalanchoe blossfeldiana",
    description: "Flowering succulent with colorful blooms.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "18-30°C",
      sunlight: "Bright light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },

  {
    image: "/images/SucculentsCacti/Agave.jpg",
    name: "Agave",
    scientificName: "Agave americana",
    description: "Large architectural succulent with spiky leaves.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-40°C",
      sunlight: "Full sun",
      waterFrequency: "Monthly",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹599",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },
  {
    image: "/images/SucculentsCacti/ZebraPlant.jpg",
    name: "Zebra Plant",
    scientificName: "Haworthiopsis fasciata",
    description: "Striped succulent with attractive compact growth.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-28°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free pot"],
  },
  {
    image: "/images/SucculentsCacti/CrownOfThorns.jpg",
    name: "Crown of Thorns",
    scientificName: "Euphorbia milii",
    description: "Flowering succulent with thorny stems.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹399",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },
  {
    image: "/images/SucculentsCacti/Sedum.jpg",
    name: "Sedum (Burro's Tail)",
    scientificName: "Sedum morganianum",
    description: "Trailing succulent ideal for hanging baskets.",
    features: {
      rawMaterial: ["Cactus mix"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Hanging pot included"],
  },
  {
    image: "/images/SucculentsCacti/StringOfPearls.jpg",
    name: "String of Pearls",
    scientificName: "Curio rowleyanus",
    description: "Unique trailing succulent with bead-like leaves.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-30°C",
      sunlight: "Bright indirect",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Hanging basket included"],
  },
  {
    image: "/images/SucculentsCacti/Portulaca.jpg",
    name: "Portulaca (Moss Rose)",
    scientificName: "Portulaca grandiflora",
    description: "Colorful flowering succulent ideal for sunny gardens.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-38°C",
      sunlight: "Full sun",
      waterFrequency: "Every 3 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹199",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 get 10% off"],
  },
  {
    image: "/images/SucculentsCacti/Adenium.jpg",
    name: "Adenium (Desert Rose)",
    scientificName: "Adenium obesum",
    description: "Thick-trunked flowering succulent.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "20-35°C",
      sunlight: "Full sun",
      waterFrequency: "Weekly",
      oxygenEmission: "Low",
      difficulty: "medium",
    },
    price: "₹599",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },
  {
    image: "/images/SucculentsCacti/PaddlePlant.jpg",
    name: "Paddle Plant",
    scientificName: "Kalanchoe luciae",
    description: "Flat paddle-shaped leaves with red edges.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-32°C",
      sunlight: "Bright light",
      waterFrequency: "Every 2 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹349",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/SucculentsCacti/IndianSpurges.jpg",
    name: "Indian Spurges",
    scientificName: "Euphorbia neriifolia",
    description: "Medicinal succulent with thick upright stems.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-40°C",
      sunlight: "Full sun",
      waterFrequency: "Every 3 weeks",
      oxygenEmission: "Low",
      difficulty: "easy",
    },
    price: "₹399",
    deliveryBy: "4-6 days",
    offers: ["Free pot"],
  },
];

const medicinalPlants = [
  {
    image: "/images/MedicinalHerbal/Tulsi.jpg",
    name: "Tulsi",
    scientificName: "Ocimum tenuiflorum",
    description:
      "Holy Basil widely used in Ayurveda for boosting immunity and treating respiratory disorders.",
    features: {
      rawMaterial: ["Herbal soil mix", "Plastic pot"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Every 2-3 days",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹199",
    originalPrice: "₹299",
    deliveryBy: "2-4 days",
    offers: ["10% off", "Free plastic pot"],
  },
  {
    image: "/images/MedicinalHerbal/Neem.jpg",
    name: "Neem",
    scientificName: "Azadirachta indica",
    description:
      "Powerful medicinal tree known for antibacterial and blood-purifying properties.",
    features: {
      rawMaterial: ["Garden soil", "Grow bag"],
      temperature: "25-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹249",
    originalPrice: "₹399",
    deliveryBy: "3-5 days",
    offers: ["Free grow bag"],
  },
  {
    image: "/images/MedicinalHerbal/AloeVera.jpg",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    description:
      "Succulent medicinal plant used for skin healing and digestive health.",
    features: {
      rawMaterial: ["Cactus soil"],
      temperature: "18-35°C",
      sunlight: "Bright sunlight",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹399",
    deliveryBy: "2-4 days",
    offers: ["Free terracotta pot"],
  },
  {
    image: "/images/MedicinalHerbal/Ashwagandha.jpg",
    name: "Ashwagandha",
    scientificName: "Withania somnifera",
    description:
      "Adaptogenic herb that helps reduce stress and improve stamina.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["15% off"],
  },
  {
    image: "/images/MedicinalHerbal/Giloy.jpg",
    name: "Giloy",
    scientificName: "Tinospora cordifolia",
    description:
      "Climbing medicinal plant known for boosting immunity and reducing fever.",
    features: {
      rawMaterial: ["Garden soil", "Support stick"],
      temperature: "20-35°C",
      sunlight: "Partial sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹219",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 get 10% off"],
  },
  {
    image: "/images/MedicinalHerbal/Amla.jpg",
    name: "Amla",
    scientificName: "Phyllanthus emblica",
    description:
      "Indian Gooseberry rich in Vitamin C and widely used in Ayurvedic medicine.",
    features: {
      rawMaterial: ["Loamy soil", "Grow bag"],
      temperature: "20-38°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Free organic fertilizer"],
  },
  {
    image: "/images/MedicinalHerbal/Ginger.jpg",
    name: "Ginger",
    scientificName: "Zingiber officinale",
    description:
      "Medicinal rhizome used to improve digestion and relieve cold and cough.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-30°C",
      sunlight: "Partial sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹159",
    originalPrice: "₹249",
    deliveryBy: "2-4 days",
    offers: ["10% off"],
  },
  {
    image: "/images/MedicinalHerbal/Garlic.jpg",
    name: "Garlic",
    scientificName: "Allium sativum",
    description:
      "Medicinal bulb known for improving heart health and immunity.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "15-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹149",
    originalPrice: "₹229",
    deliveryBy: "2-4 days",
    offers: ["Buy 1 get 1 50% off"],
  },
  {
    image: "/images/MedicinalHerbal/Brahmi.jpg",
    name: "Brahmi",
    scientificName: "Bacopa monnieri",
    description:
      "Memory-enhancing herb used in Ayurveda for cognitive improvement.",
    features: {
      rawMaterial: ["Moist soil mix"],
      temperature: "20-35°C",
      sunlight: "Partial sunlight",
      waterFrequency: "Keep moist",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹229",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Free herbal guide"],
  },
  {
    image: "/images/MedicinalHerbal/Shankhpushpi.jpg",
    name: "Shankhpushpi",
    scientificName: "Convolvulus pluricaulis",
    description:
      "Traditional brain tonic herb that enhances concentration and memory.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹259",
    originalPrice: "₹379",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/MedicinalHerbal/Arjun.jpg",
    name: "Arjun",
    scientificName: "Terminalia arjuna",
    description: "Medicinal tree whose bark is widely used for heart health.",
    features: {
      rawMaterial: ["Garden soil"],
      temperature: "25-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "4-6 days",
    offers: ["Free grow bag"],
  },
  {
    image: "/images/MedicinalHerbal/Bael.jpg",
    name: "Bael",
    scientificName: "Aegle marmelos",
    description:
      "Sacred medicinal fruit tree used for digestive and gut health.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-38°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },
  {
    image: "/images/MedicinalHerbal/Sarpagandha.jpg",
    name: "Sarpagandha",
    scientificName: "Rauvolfia serpentina",
    description: "Traditional medicinal shrub used for managing hypertension.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-30°C",
      sunlight: "Partial sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹319",
    originalPrice: "₹459",
    deliveryBy: "3-5 days",
    offers: ["Free herbal care tips"],
  },
  {
    image: "/images/MedicinalHerbal/SafedMusli.jpg",
    name: "Safed Musli",
    scientificName: "Chlorophytum borivilianum",
    description:
      "Rare Ayurvedic herb valued for vitality and rejuvenation properties.",
    features: {
      rawMaterial: ["Organic soil mix"],
      temperature: "20-32°C",
      sunlight: "Partial sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "hard",
    },
    price: "₹399",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["20% off limited stock"],
  },
  {
    image: "/images/MedicinalHerbal/Kalmegh.jpg",
    name: "Kalmegh",
    scientificName: "Andrographis paniculata",
    description:
      "Bitter medicinal herb known for liver detox and immunity support.",
    features: {
      rawMaterial: ["Well-draining soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹199",
    originalPrice: "₹299",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },
  {
    image: "/images/MedicinalHerbal/Isabgol.jpg",
    name: "Isabgol",
    scientificName: "Plantago ovata",
    description: "Medicinal seed plant widely used as a natural digestive aid.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "15-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹229",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Free seed packet"],
  },
];

const fruitsPlants = [
  {
    image: "/images/Fruit/Mango.jpg",
    name: "Mango",
    scientificName: "Mangifera indica",
    description:
      "King of fruits in India, known for its sweet tropical flavor.",
    features: {
      rawMaterial: ["Loamy soil", "Organic compost"],
      temperature: "24-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },
  {
    image: "/images/Fruit/Banana.jpg",
    name: "Banana",
    scientificName: "Musa paradisiaca",
    description: "Fast-growing tropical fruit plant rich in potassium.",
    features: {
      rawMaterial: ["Moist fertile soil"],
      temperature: "25-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free grow bag"],
  },
  {
    image: "/images/Fruit/Apple.jpg",
    name: "Apple",
    scientificName: "Malus domestica",
    description: "Temperate fruit tree producing crisp and nutritious apples.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "10-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },
  {
    image: "/images/Fruit/Guava.jpg",
    name: "Guava",
    scientificName: "Psidium guajava",
    description: "Vitamin C-rich tropical fruit with sweet aroma.",
    features: {
      rawMaterial: ["Sandy loam soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Free organic fertilizer"],
  },

  {
    image: "/images/Fruit/Orange.jpg",
    name: "Orange",
    scientificName: "Citrus sinensis",
    description: "Citrus fruit rich in Vitamin C and antioxidants.",
    features: {
      rawMaterial: ["Citrus soil mix"],
      temperature: "18-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/Fruit/Lemon.jpg",
    name: "Lemon",
    scientificName: "Citrus limon",
    description: "Small citrus fruit used in beverages and cooking.",
    features: {
      rawMaterial: ["Well-drained citrus soil"],
      temperature: "20-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/Fruit/Pomegranate.jpg",
    name: "Pomegranate",
    scientificName: "Punica granatum",
    description: "Fruit rich in antioxidants and heart-healthy nutrients.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },

  {
    image: "/images/Fruit/Papaya.jpg",
    name: "Papaya",
    scientificName: "Carica papaya",
    description: "Fast-growing fruit plant known for digestive benefits.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "22-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free compost"],
  },

  {
    image: "/images/Fruit/Grapes.jpg",
    name: "Grapes",
    scientificName: "Vitis vinifera",
    description: "Climbing vine producing sweet grape clusters.",
    features: {
      rawMaterial: ["Loamy soil", "Support trellis"],
      temperature: "18-32°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Free support stick"],
  },
  {
    image: "/images/Fruit/Sapota.jpg",
    name: "Sapota / Chikoo",
    scientificName: "Manilkara zapota",
    description: "Sweet brown tropical fruit rich in fiber and natural sugars.",
    features: {
      rawMaterial: ["Well-drained loamy soil"],
      temperature: "22-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },

  {
    image: "/images/Fruit/CustardApple.jpg",
    name: "Custard Apple / Sitaphal",
    scientificName: "Annona squamosa",
    description: "Creamy textured fruit with sweet aromatic pulp.",
    features: {
      rawMaterial: ["Sandy loam soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Free organic fertilizer"],
  },

  {
    image: "/images/Fruit/Pineapple.jpg",
    name: "Pineapple",
    scientificName: "Ananas comosus",
    description:
      "Tropical fruit known for its sweet-tangy taste and vitamin C.",
    features: {
      rawMaterial: ["Sandy soil", "Organic compost"],
      temperature: "22-32°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/Fruit/Jackfruit.jpg",
    name: "Jackfruit",
    scientificName: "Artocarpus heterophyllus",
    description:
      "Large tropical fruit used both raw and ripe in Indian cuisine.",
    features: {
      rawMaterial: ["Deep loamy soil"],
      temperature: "24-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/Fruit/Litchi.jpg",
    name: "Litchi",
    scientificName: "Litchi chinensis",
    description: "Juicy summer fruit with sweet floral flavor.",
    features: {
      rawMaterial: ["Well-drained loamy soil"],
      temperature: "20-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/Fruit/Watermelon.jpg",
    name: "Watermelon",
    scientificName: "Citrullus lanatus",
    description: "Refreshing summer fruit with high water content.",
    features: {
      rawMaterial: ["Sandy loam soil"],
      temperature: "25-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Free seeds pack"],
  },

  {
    image: "/images/Fruit/Muskmelon.jpg",
    name: "Muskmelon",
    scientificName: "Cucumis melo",
    description: "Sweet aromatic melon ideal for summer cultivation.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "24-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/Fruit/Amla.jpg",
    name: "Amla / Indian Gooseberry",
    scientificName: "Phyllanthus emblica",
    description: "Highly nutritious fruit rich in Vitamin C and antioxidants.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },

  {
    image: "/images/Fruit/Bael.jpg",
    name: "Bael",
    scientificName: "Aegle marmelos",
    description: "Sacred medicinal fruit known for digestive benefits.",
    features: {
      rawMaterial: ["Dry loamy soil"],
      temperature: "25-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },

  {
    image: "/images/Fruit/Ber.jpg",
    name: "Ber / Indian Jujube",
    scientificName: "Ziziphus mauritiana",
    description: "Hardy fruit tree producing sweet and tangy berries.",
    features: {
      rawMaterial: ["Sandy loam soil"],
      temperature: "20-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free grow bag"],
  },

  {
    image: "/images/Fruit/Fig.jpg",
    name: "Fig / Anjeer",
    scientificName: "Ficus carica",
    description: "Soft fruit consumed fresh or dried, rich in fiber.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "15-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },

  {
    image: "/images/Fruit/Jamun.jpg",
    name: "Jamun / Indian Blackberry",
    scientificName: "Syzygium cumini",
    description: "Purple fruit known for blood sugar regulating properties.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },

  {
    image: "/images/Fruit/Tamarind.jpg",
    name: "Tamarind / Imli",
    scientificName: "Tamarindus indica",
    description: "Tangy pulp fruit widely used in Indian cuisine.",
    features: {
      rawMaterial: ["Deep loamy soil"],
      temperature: "25-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Free compost"],
  },

  {
    image: "/images/Fruit/WoodApple.jpg",
    name: "Wood Apple / Kaitha",
    scientificName: "Limonia acidissima",
    description: "Hard-shelled fruit valued for digestive benefits.",
    features: {
      rawMaterial: ["Dry sandy soil"],
      temperature: "25-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },

  {
    image: "/images/Fruit/DragonFruit.jpg",
    name: "Dragon Fruit",
    scientificName: "Hylocereus undatus",
    description: "Exotic cactus fruit rich in antioxidants.",
    features: {
      rawMaterial: ["Sandy soil", "Support structure"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/Fruit/Strawberry.jpg",
    name: "Strawberry",
    scientificName: "Fragaria × ananassa",
    description: "Bright red berry rich in Vitamin C.",
    features: {
      rawMaterial: ["Well-drained soil", "Organic compost"],
      temperature: "15-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/Fruit/Kiwi.jpg",
    name: "Kiwi",
    scientificName: "Actinidia deliciosa",
    description: "Nutrient-rich fruit with tangy-sweet flavor.",
    features: {
      rawMaterial: ["Well-drained soil", "Support trellis"],
      temperature: "10-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "5-7 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/Fruit/Pear.jpg",
    name: "Pear",
    scientificName: "Pyrus communis",
    description: "Juicy temperate fruit rich in fiber.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "10-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },

  {
    image: "/images/Fruit/Plum.jpg",
    name: "Plum",
    scientificName: "Prunus domestica",
    description: "Sweet and tart stone fruit suitable for cooler climates.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "10-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },

  {
    image: "/images/Fruit/Cherry.jpg",
    name: "Cherry",
    scientificName: "Prunus avium",
    description: "Small red fruit packed with antioxidants.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "5-20°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "hard",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "5-7 days",
    offers: ["Premium plant"],
  },
];

const airPurifierPlants = [
  {
    image: "/images/AirPurifier/SnakePlant.jpg",
    name: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    description:
      "Highly effective indoor air purifier known for absorbing toxins and releasing oxygen at night.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Every 10-14 days",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "3-5 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/MoneyPlant.jpg",
    name: "Money Plant / Pothos",
    scientificName: "Epipremnum aureum",
    description:
      "Popular indoor vine known for removing indoor pollutants and easy maintenance.",
    features: {
      rawMaterial: ["Water or soil"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free grow pot"],
  },

  {
    image: "/images/AirPurifier/PeaceLily.jpg",
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    description:
      "Beautiful flowering plant known for removing indoor toxins and improving humidity.",
    features: {
      rawMaterial: ["Moist well-drained soil"],
      temperature: "18-28°C",
      sunlight: "Low to medium light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/AirPurifier/ArecaPalm.jpg",
    name: "Areca Palm",
    scientificName: "Dypsis lutescens",
    description:
      "Natural air humidifier that effectively removes airborne toxins.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-30°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "5-7 days",
    offers: ["Free fertilizer"],
  },

  {
    image: "/images/AirPurifier/AloeVera.jpg",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis Miller",
    description:
      "Medicinal succulent that purifies air and has skin-healing properties.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "18-32°C",
      sunlight: "Bright sunlight",
      waterFrequency: "Every 10 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },
  {
    image: "/images/AirPurifier/SpiderPlant.jpg",
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    description:
      "Hardy indoor plant known for removing carbon monoxide and toxins.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },

  {
    image: "/images/AirPurifier/RubberPlant.jpg",
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    description:
      "Large glossy-leaf plant effective in improving indoor air quality.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "16-28°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/ZZPlant.jpg",
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    description:
      "Low-maintenance plant that tolerates low light and purifies air.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Low to medium light",
      waterFrequency: "Every 10-14 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["Free grow pot"],
  },

  {
    image: "/images/AirPurifier/BostonFern.jpg",
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    description:
      "Lush fern known for improving humidity and removing pollutants.",
    features: {
      rawMaterial: ["Moist rich soil"],
      temperature: "18-26°C",
      sunlight: "Indirect light",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/AirPurifier/ChineseEvergreen.jpg",
    name: "Chinese Evergreen",
    scientificName: "Aglaonema commutatum",
    description:
      "Decorative foliage plant that thrives in low light and purifies air.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Low to medium light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/BambooPalm.jpg",
    name: "Bamboo Palm",
    scientificName: "Chamaedorea seifrizii",
    description: "Elegant palm plant known for filtering indoor toxins.",
    features: {
      rawMaterial: ["Moist well-drained soil"],
      temperature: "20-30°C",
      sunlight: "Indirect light",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "5-7 days",
    offers: ["Free fertilizer"],
  },

  {
    image: "/images/AirPurifier/Dracaena.jpg",
    name: "Dracaena",
    scientificName: "Dracaena fragrans",
    description:
      "Popular indoor plant known for removing formaldehyde from air.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-28°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },

  {
    image: "/images/AirPurifier/Anthurium.jpg",
    name: "Anthurium",
    scientificName: "Anthurium andraeanum",
    description: "Flowering plant known for improving indoor air humidity.",
    features: {
      rawMaterial: ["Moist organic soil"],
      temperature: "20-30°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "4-6 days",
    offers: ["Free decorative pot"],
  },

  {
    image: "/images/AirPurifier/WeepingFig.jpg",
    name: "Weeping Fig",
    scientificName: "Ficus benjamina",
    description: "Graceful indoor tree that improves indoor air quality.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "16-28°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹549",
    originalPrice: "₹749",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/Philodendron.jpg",
    name: "Philodendron",
    scientificName: "Philodendron hederaceum",
    description: "Easy-care indoor vine effective in removing toxins.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/AirPurifier/GerberaDaisy.jpg",
    name: "Gerbera Daisy",
    scientificName: "Gerbera jamesonii",
    description: "Colorful flowering plant known for oxygen release at night.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "15-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/AirPurifier/EnglishIvy.jpg",
    name: "English Ivy",
    scientificName: "Hedera helix",
    description: "Climbing vine known for reducing airborne mold.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "10-25°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/ParlorPalm.jpg",
    name: "Parlor Palm",
    scientificName: "Chamaedorea elegans",
    description: "Compact palm ideal for indoor air purification.",
    features: {
      rawMaterial: ["Moist well-drained soil"],
      temperature: "18-28°C",
      sunlight: "Low to medium light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["Free grow bag"],
  },

  {
    image: "/images/AirPurifier/Tulsi.jpg",
    name: "Tulsi",
    scientificName: "Ocimum tenuiflorum",
    description:
      "Sacred medicinal plant known for purifying air and boosting immunity.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },

  {
    image: "/images/AirPurifier/Neem.jpg",
    name: "Neem",
    scientificName: "Azadirachta indica",
    description:
      "Powerful medicinal tree known for air purification properties.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "25-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/Peepal.jpg",
    name: "Peepal",
    scientificName: "Ficus religiosa",
    description: "Sacred tree believed to produce oxygen even at night.",
    features: {
      rawMaterial: ["Deep loamy soil"],
      temperature: "20-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Very High",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "5-7 days",
    offers: ["Free organic fertilizer"],
  },

  {
    image: "/images/AirPurifier/Banyan.jpg",
    name: "Banyan",
    scientificName: "Ficus benghalensis",
    description: "Large native tree known for excellent oxygen production.",
    features: {
      rawMaterial: ["Deep fertile soil"],
      temperature: "20-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "Very High",
      difficulty: "hard",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "6-8 days",
    offers: ["Premium plant"],
  },

  {
    image: "/images/AirPurifier/Ashoka.jpg",
    name: "Ashoka",
    scientificName: "Polyalthia longifolia",
    description: "Ornamental tree effective in reducing noise and pollution.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-38°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },

  {
    image: "/images/AirPurifier/Arjuna.jpg",
    name: "Arjuna",
    scientificName: "Terminalia arjuna",
    description: "Medicinal tree known for environmental and health benefits.",
    features: {
      rawMaterial: ["Loamy soil"],
      temperature: "20-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/AirPurifier/Kadamba.jpg",
    name: "Kadamba",
    scientificName: "Neolamarckia cadamba",
    description: "Fast-growing native tree known for environmental benefits.",
    features: {
      rawMaterial: ["Moist fertile soil"],
      temperature: "22-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "5-7 days",
    offers: ["Free compost"],
  },
];

const giftPlants = [
  {
    image: "/images/giftPlant/SnakePlant.jpg",
    name: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    description:
      "Low-maintenance air-purifying plant perfect for gifting and indoor décor.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Every 10-14 days",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "3-5 days",
    offers: ["15% off"],
  },

  {
    image: "/images/giftPlant/MoneyPlant.jpg",
    name: "Money Plant / Pothos",
    scientificName: "Epipremnum aureum",
    description:
      "Symbol of prosperity and good luck, ideal for home and office gifting.",
    features: {
      rawMaterial: ["Water or soil"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["Free decorative pot"],
  },

  {
    image: "/images/giftPlant/PeaceLily.jpg",
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    description:
      "Elegant flowering plant that symbolizes peace and positivity.",
    features: {
      rawMaterial: ["Moist well-drained soil"],
      temperature: "18-28°C",
      sunlight: "Low to medium light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "4-6 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/giftPlant/ArecaPalm.jpg",
    name: "Areca Palm",
    scientificName: "Dypsis lutescens",
    description: "Beautiful indoor palm that enhances décor and purifies air.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-30°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Twice weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "5-7 days",
    offers: ["Free fertilizer"],
  },

  {
    image: "/images/giftPlant/AloeVera.jpg",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis Miller",
    description:
      "Medicinal succulent plant known for skin and health benefits.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "18-32°C",
      sunlight: "Bright sunlight",
      waterFrequency: "Every 10 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/giftPlant/ZZPlant.jpg",
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    description:
      "Hardy plant that thrives in low light and requires minimal care.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Low to bright indirect light",
      waterFrequency: "Every 2-3 weeks",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["12% off"],
  },

  {
    image: "/images/giftPlant/SpiderPlant.jpg",
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    description: "Fast-growing plant known for removing indoor pollutants.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "15-27°C",
      sunlight: "Indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹279",
    originalPrice: "₹399",
    deliveryBy: "3-5 days",
    offers: ["Free hanging pot"],
  },

  {
    image: "/images/giftPlant/RubberPlant.jpg",
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    description: "Glossy-leaved ornamental plant ideal for modern interiors.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "16-30°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹499",
    originalPrice: "₹699",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/giftPlant/JadePlant.jpg",
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    description: "Succulent symbolizing wealth and prosperity.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "18-28°C",
      sunlight: "Bright sunlight",
      waterFrequency: "Every 10-15 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹399",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },

  {
    image: "/images/giftPlant/LuckyBamboo.jpg",
    name: "Lucky Bamboo",
    scientificName: "Dracaena sanderiana",
    description: "Popular feng shui plant symbolizing luck and fortune.",
    features: {
      rawMaterial: ["Water"],
      temperature: "18-30°C",
      sunlight: "Indirect sunlight",
      waterFrequency: "Change water weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "3-5 days",
    offers: ["Decorative glass vase"],
  },
  {
    image: "/images/giftPlant/Orchid.jpg",
    name: "Orchid",
    scientificName: "Phalaenopsis amabilis",
    description:
      "Exotic flowering plant known for long-lasting elegant blooms.",
    features: {
      rawMaterial: ["Orchid potting mix"],
      temperature: "18-28°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹699",
    originalPrice: "₹899",
    deliveryBy: "4-6 days",
    offers: ["Free decorative wrap"],
  },

  {
    image: "/images/giftPlant/Anthurium.jpg",
    name: "Anthurium",
    scientificName: "Anthurium andraeanum",
    description: "Vibrant heart-shaped flowering plant ideal for gifting.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-30°C",
      sunlight: "Indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "4-6 days",
    offers: ["12% off"],
  },

  {
    image: "/images/giftPlant/GerberaDaisy.jpg",
    name: "Gerbera Daisy",
    scientificName: "Gerbera jamesonii",
    description: "Bright and cheerful flowering plant symbolizing happiness.",
    features: {
      rawMaterial: ["Rich well-drained soil"],
      temperature: "15-25°C",
      sunlight: "Full sunlight",
      waterFrequency: "Twice weekly",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "3-5 days",
    offers: ["10% cashback"],
  },

  {
    image: "/images/giftPlant/RosePlant.jpg",
    name: "Rose Plant",
    scientificName: "Rosa indica",
    description: "Classic flowering plant representing love and admiration.",
    features: {
      rawMaterial: ["Fertile soil"],
      temperature: "15-28°C",
      sunlight: "Full sunlight",
      waterFrequency: "Every 2-3 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "3-5 days",
    offers: ["Free greeting card"],
  },

  {
    image: "/images/giftPlant/Kalanchoe.jpg",
    name: "Kalanchoe",
    scientificName: "Kalanchoe blossfeldiana",
    description: "Compact flowering succulent with vibrant blooms.",
    features: {
      rawMaterial: ["Sandy soil"],
      temperature: "15-30°C",
      sunlight: "Bright sunlight",
      waterFrequency: "Every 7-10 days",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹399",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 10%"],
  },

  {
    image: "/images/giftPlant/Bougainvillea.jpg",
    name: "Bougainvillea",
    scientificName: "Bougainvillea glabra",
    description:
      "Colorful outdoor flowering plant ideal for balconies and gardens.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Every 3-4 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹399",
    originalPrice: "₹549",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/giftPlant/Tulsi.jpg",
    name: "Tulsi",
    scientificName: "Ocimum tenuiflorum",
    description:
      "Sacred medicinal herb known for health and spiritual benefits.",
    features: {
      rawMaterial: ["Fertile soil"],
      temperature: "20-35°C",
      sunlight: "Full sunlight",
      waterFrequency: "Daily (light watering)",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹199",
    originalPrice: "₹299",
    deliveryBy: "3-5 days",
    offers: ["Free organic seeds"],
  },

  {
    image: "/images/giftPlant/Neem.jpg",
    name: "Neem",
    scientificName: "Azadirachta indica",
    description:
      "Medicinal tree plant known for air purification and healing properties.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "20-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Every 3-4 days",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹249",
    originalPrice: "₹349",
    deliveryBy: "5-7 days",
    offers: ["10% off"],
  },

  {
    image: "/images/giftPlant/Peepal.jpg",
    name: "Peepal",
    scientificName: "Ficus religiosa",
    description:
      "Sacred tree known for high oxygen release and spiritual value.",
    features: {
      rawMaterial: ["Fertile soil"],
      temperature: "20-40°C",
      sunlight: "Full sunlight",
      waterFrequency: "Every 3-4 days",
      oxygenEmission: "Very High",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹399",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/giftPlant/BambooPalm.jpg",
    name: "Bamboo Palm",
    scientificName: "Chamaedorea seifrizii",
    description: "Elegant indoor palm known for air purification.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "medium",
    },
    price: "₹599",
    originalPrice: "₹799",
    deliveryBy: "4-6 days",
    offers: ["Free fertilizer"],
  },

  {
    image: "/images/giftPlant/Aglaonema.jpg",
    name: "Aglaonema / Chinese Evergreen",
    scientificName: "Aglaonema commutatum",
    description: "Low-light tolerant decorative foliage plant.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-28°C",
      sunlight: "Low to medium light",
      waterFrequency: "Weekly",
      oxygenEmission: "High",
      difficulty: "easy",
    },
    price: "₹449",
    originalPrice: "₹599",
    deliveryBy: "4-6 days",
    offers: ["12% off"],
  },

  {
    image: "/images/giftPlant/Philodendron.jpg",
    name: "Philodendron",
    scientificName: "Philodendron hederaceum",
    description: "Popular trailing indoor plant with heart-shaped leaves.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹329",
    originalPrice: "₹449",
    deliveryBy: "3-5 days",
    offers: ["10% off"],
  },

  {
    image: "/images/giftPlant/Syngonium.jpg",
    name: "Syngonium / Arrowhead Plant",
    scientificName: "Syngonium podophyllum",
    description: "Attractive indoor foliage plant ideal for desks and shelves.",
    features: {
      rawMaterial: ["Well-drained soil"],
      temperature: "18-30°C",
      sunlight: "Indirect light",
      waterFrequency: "Weekly",
      oxygenEmission: "Medium",
      difficulty: "easy",
    },
    price: "₹299",
    originalPrice: "₹399",
    deliveryBy: "3-5 days",
    offers: ["Buy 2 save 5%"],
  },

  {
    image: "/images/giftPlant/FicusBonsai.jpg",
    name: "Ficus Bonsai",
    scientificName: "Ficus microcarpa",
    description:
      "Miniature ornamental bonsai tree symbolizing harmony and balance.",
    features: {
      rawMaterial: ["Bonsai soil mix"],
      temperature: "18-30°C",
      sunlight: "Bright indirect light",
      waterFrequency: "Every 3-4 days",
      oxygenEmission: "Medium",
      difficulty: "hard",
    },
    price: "₹999",
    originalPrice: "₹1299",
    deliveryBy: "5-7 days",
    offers: ["15% off"],
  },

  {
    image: "/images/giftPlant/Lavender.jpg",
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    description:
      "Fragrant flowering plant known for calming aroma and medicinal uses.",
    features: {
      rawMaterial: ["Sandy well-drained soil"],
      temperature: "15-30°C",
      sunlight: "Full sunlight",
      waterFrequency: "Every 4-5 days",
      oxygenEmission: "Medium",
      difficulty: "medium",
    },
    price: "₹349",
    originalPrice: "₹499",
    deliveryBy: "4-6 days",
    offers: ["10% off"],
  },
];

// ✅ Fix 1: Add category to ALL
indoorPlants.forEach((plant) => (plant.category = "Indoor Plants"));
outdoorPlantsData.forEach((plant) => (plant.category = "Outdoor Plants"));
floweringPlantsData.forEach((plant) => (plant.category = "Flowering Plants"));
succulentsCactiData.forEach((plant) => (plant.category = "Succulents Cacti"));
medicinalPlants.forEach((plant) => (plant.category = "Medicinal Herbal"));
fruitsPlants.forEach((plant) => (plant.category = "Fruit Plants"));
airPurifierPlants.forEach((plant) => (plant.category = "Air Purifying"));
giftPlants.forEach((plant) => (plant.category = "Gift Plants"));

async function seedAllPlants() {
  try {
    // ✅ Fix 2: Clear + Single insertMany (NO duplicates/multiple calls)
    await Plant.deleteMany({});
    console.log("🗑️  Cleared existing plants");

    const allPlants = [
      ...indoorPlants,
      ...outdoorPlantsData,
      ...floweringPlantsData,
      ...succulentsCactiData,
      ...medicinalPlants,
      ...fruitsPlants,
      ...airPurifierPlants,
      ...giftPlants,
    ];
    const result = await Plant.insertMany(allPlants);

    console.log(`✅ Seeded ${result.length} plants!`);
    // console.log(
    //   `📊 Indoor: ${indoorPlants.length}, Outdoor: ${outdoorPlantsData.length}`,
    // );

    // Verify saved
    const count = await Plant.countDocuments();
    console.log(`✅ Database has ${count} plants`);

    mongoose.connection.close();
  } catch (error) {
    console.error("❌ Seed ERROR:", error);
    mongoose.connection.close();
  }
}

seedAllPlants();
